# Generated by Django 2.0.2 on 2018-02-25 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bashprocess',
            old_name='command',
            new_name='script',
        ),
    ]
